deps/hsa/build.jl
deps/rocm-external/build.jl
deps/rocm-external/rocblas_interface.jl

Addresses some things noticed in #29

Small cleanup in deps/

---

docs/src/memory.md
src/device/gcn/memory_dynamic.jl
src/device/runtime.jl
src/execution.jl
test/device/memory.jl

I didn't realize the return type was supposed to be a `Ptr{Cvoid}`...

Fixed malloc return type

---

src/kernel.jl
test/device/launch.jl

Allow 0-argument kernels

---

test/runtests.jl

Test extlibs are available under CI

---

src/device/gcn/output.jl
src/device/runtime.jl
src/execution.jl

~Hopefully we can also get these enabled for regular `julia`: https://github.com/JuliaGPU/GPUCompiler.jl/issues/142~
Works with `julia -g2`

Enable device stacktraces

---

deps/build.jl
docs/src/index.md
docs/src/quickstart.md
src/AMDGPU.jl
src/hsa/HSA.jl
src/hsa/libhsa_api.jl

Fixes #93 , which also gets us working ROCgdb support!

Look for libhsa-runtime64.so.1

---

src/kernel.jl
src/queue.jl
test/device/launch.jl

Fix kernel argument alignment

---

src/AMDGPU.jl
src/agent.jl
src/array.jl
src/broadcast.jl
src/device/gcn/indexing.jl
src/hsa/libhsa_api.jl
src/mapreduce.jl
src/runtime.jl
test/hsa/agent.jl
test/runtests.jl

The long-awaited `GPUArrays.mapreducedim!` arrives! This implementation was copied and modified from oneAPI. We should be able to start enabling more tests, now that we have this.

Add mapreducedim!

---

.github/workflows/CompatHelper.yml

Copied from CUDA, hopefully it works!

Fix CompatHelper config

---

docs/src/quickstart.md
src/execution.jl
src/execution_utils.jl
test/device/launch.jl

Check groupsize, add group/grid docs

---

Project.toml
deps/build.jl
src/kernel.jl
src/queue.jl
src/runtime.jl
src/signal.jl
test/device/launch.jl

For https://github.com/JuliaGPU/KernelAbstractions.jl/pull/209
@vchuravy

KernelAbstractions support

---

src/AMDGPU.jl
src/extras.jl
src/kernel.jl
src/queue.jl

Fix packet launch

---

src/array.jl
test/rocarray/base.jl
test/runtests.jl

Fix copyto! on view; include offset

---

Project.toml
deps/loaddeps.jl
docs/src/queues_signals.md
src/AMDGPU.jl
src/exceptions.jl
src/execution.jl
src/execution_utils.jl
src/query.jl
src/queue.jl
src/runtime.jl
src/statussignal.jl
test/device/exceptions.jl
test/device/queries.jl
test/runtests.jl

Related to https://github.com/JuliaGPU/AMDGPU.jl/issues/139

Add support for active_kernels

---

deps/build.jl
deps/loaddeps.jl
src/AMDGPU.jl
src/device/runtime.jl
src/utils.jl

Make build failure logging more verbose

---

src/array.jl
test/rocarray/base.jl

ROCArray: Add unsafe_wrap

---

src/array.jl
src/memory.jl
test/rocarray/base.jl

Mem: Fix DL/UL/TX for wrapped ptr

---

src/AMDGPU.jl

Changed launch! export to launch to be consistent with CUDA.jl.

Remove launch export

---

src/device/gcn/indexing.jl
src/launch.jl
test/device/launch.jl

launch: Fix groupsize dimension check

---

docs/src/api.md
docs/src/quickstart.md
src/AMDGPU.jl
src/array.jl
src/deprecations.jl
src/device/gcn/indexing.jl
src/device/gcn/synchronization.jl
src/mapreduce.jl
test/codegen/synchronization.jl
test/device/indexing.jl
test/device/output.jl
test/device/vadd.jl
test/device/wavefront.jl

Rename gridDim to gridItemDim
Export sync_workgroup

Re-export indexing intrinsics

---

docs/src/queues_signals.md
src/queue.jl
test/hsa/queue.jl
test/runtests.jl

queue: Allow setting priority from ctor

---

src/device/gcn/helpers.jl

Fixes issues with Revise not working
Copied from https://github.com/JuliaGPU/CUDA.jl/pull/1112

Don't embed the method table in the AST

---

src/device.jl
test/hsa/device.jl

device: Add ROCDevice() ctor

---

src/mapreduce.jl

New PR for adding ```mapreducedim!``` support for ```AnyROCArray```.

Mapreducedim support for AnyROCArray

---

.buildkite/pipeline.yml
deps/bindeps.jl
src/utils.jl
test/Project.toml
test/hsa/utils.jl
test/runtests.jl
test/setup.jl

This uses Distributed to parallelize the tests, in the hopes of having CI jobs which don't take >3hrs to run.
Todo:

Parallelize tests

---

src/AMDGPU.jl

Oops :sweat_smile: 
Fixes #315

random: Load definitions without rocRAND

---

src/array.jl
test/rocarray/base.jl

Adds support for resize! for ROCVector.

Resize! support

---

src/device/gcn/math.jl
test/device/math.jl

Add sincos/sincospi/frexp/ldexp intrinsics

---

docs/src/memory.md
src/AMDGPU.jl
src/array.jl
src/compiler.jl
src/device/gcn/memory_static.jl
test/device/memory.jl

Adds `@ROCDynamicLocalArray` and `@ROCStaticLocalArray` for allocating local memory.
Closes #347

Add local memory allocation helpers

---

src/device/gcn/array.jl

Make alignment generated

---

test/runtests.jl

tests: Properly unwrap Distributed exceptions

---

docs/src/queues_signals.md
src/runtime/kernel-signal.jl
src/runtime/launch.jl
src/runtime/logging.jl
src/runtime/signal.jl
test/device/deps.jl
test/logging.jl

Cuts down the cost of `ROCSignal` construction from 50us to 1us on my system.

ROCSignal: Pool signals in ctor

---

src/compiler/codegen.jl

Fixes https://github.com/JuliaGPU/AMDGPU.jl/pull/407#issuecomment-1496630396

Fix compiler timespan logging

---

src/AMDGPU.jl
src/blas/rocBLAS.jl
src/blas/wrappers.jl
src/cache.jl
src/dnn/MIOpen.jl
src/dnn/activations.jl
src/dnn/batchnorm.jl
src/dnn/convolution.jl
src/dnn/low_level.jl
src/dnn/pooling.jl
src/dnn/softmax.jl
src/runtime/sync.jl

Fixes issues with synchronization.
Additionally create generic `library_state` function which HIP based libraries can call.

Use TLS library state for MIOpen

---

.buildkite/pipeline.yml
src/compiler/codegen.jl
src/discovery_utils.jl
src/rand/random.jl
src/rand/rocRAND.jl
src/random.jl
test/rocarray/random.jl
test/runtests.jl

Launch device function tests on the main thread, to prevent hostcalls from hanging

Run tests on multiple workers again

---

gen/Manifest.toml
src/AMDGPU.jl
src/blas/rocBLAS.jl
src/solver/highlevel.jl
src/solver/librocsolver.jl
src/solver/rocSOLVER.jl
src/utils.jl
test/rocarray/solver.jl
test/runtests.jl

Fixes `qr` segfault in https://github.com/JuliaMolSim/DFTK.jl/pull/858.
Fixes `A \ b`, closes #372.

Add rocSOLVER routines

---

src/hip/libhip_common.jl

Add missing HIP error code

---

src/AMDGPU.jl

Add env variable if Navi 2 detected

---

src/AMDGPU.jl
src/accumulate.jl
src/device/gcn/memory_static.jl
src/runtime/hsa_device.jl
src/sparse/conversions.jl
src/sparse/interfaces.jl
test/rocarray/base.jl
test/rocsparse/broadcast.jl
test/rocsparse/interfaces.jl

Also fix sparse to dense conversion for CSC (wrong order of arguments).
Closes #317.
Enables additional functionality for #463.
CC: @matinraayai

Implement accumulate kernel

---

src/blas/highlevel.jl
src/blas/wrappers.jl
test/rocarray/blas.jl

Add rotate, reflect, axby functions

---

src/AMDGPU.jl
src/kernels/reverse.jl
test/rocarray/base.jl
test/rocarray/reverse.jl

Allows taking gradient of `cumsum` among other things...

Add reverse kernels

---

src/rand/random.jl

Fix rocrand rng offset

---

src/solver/highlevel.jl

We don't want to allocate the vector `tau` everytime that we perform a (reduced) QR decomposition.

[rocSOLVER] Add a method for geqrf!

---

src/blas/rocBLAS.jl
src/blas/util.jl
src/blas/wrappers.jl
src/solver/highlevel.jl
src/solver/librocsolver.jl
src/solver/rocSOLVER.jl
test/rocarray/solver.jl

Interface getrf_batched and getri_batched

---

src/discovery/utils.jl

This fixes detection for me in a ubuntu like system
This was changed in https://github.com/JuliaGPU/AMDGPU.jl/commit/5a46b4b21f4bb018c4f59ec7845423cfb69d75e8 though I'm not sure if it was on purpose
I don't have a windows machine to test this change, is the windows directory structure that different?

Fix path detection in ubuntu like systems

---

src/utils.jl
test/core_tests.jl

Fix functional

---

test/hip_rocsparse_tests.jl

Disable rocSPARSE tests

---

.github/workflows/ci.yml

Cleanup GitHub CI

---

docs/src/hostcall.md
docs/src/profiling.md
docs/src/streams.md

This PR updates the profiling doc and fixes few typos.

Update profiling doc

---

src/blas/highlevel.jl
src/blas/rocBLAS.jl
src/blas/wrappers.jl
test/rocarray/blas.jl

- For Julia 1.10 use specific LinearAlgebra wrappers.
- Add more BLAS Level 3 tests.

Update BLAS & add more BLAS tests

---

src/array.jl

A similar is implemented in CUDA.jl.
See also https://github.com/jipolanco/PencilFFTs.jl/issues/74

Implement Base.dataids(A::ROCArray)

---

test/rocsparse/interfaces.jl
test/runtests.jl

Upstream ROCm fixes made them no longer hang the machine.

Re-enable rocSPARSE & rocSOLVER tests

---

src/runtime/hip-execution.jl
src/runtime/memory/hip.jl
src/tls.jl
test/core_tests.jl
test/device/wavefront.jl

Fix context switching & minor optimizations

---

src/blas/highlevel.jl
src/blas/rocBLAS.jl
src/compiler/codegen.jl
src/device/quirks.jl
src/hip/device.jl
src/solver/highlevel.jl
test/device/memory.jl
test/device/wavefront.jl
test/device_tests.jl
test/rocarray/solver.jl
test/runtests.jl

- Remove old julia code (since we now support 1.10+).
- Increase maximum number of test runners to 4.

Add LLVM IR attributes (target cpu and target features)

---

src/solver/highlevel.jl
test/rocarray/solver.jl

Complex supports only conjugate transpose, so skip invalid tests:
https://rocm.docs.amd.com/projects/rocSOLVER/en/develop/reference/auxiliary.html#unmqr
Supersedes #609.

Add ormqr test

---

Project.toml
src/broadcast.jl
src/sparse/array.jl
test/rocarray/base.jl
test/rocsparse/interfaces.jl

- Closes #703 
- Fix broadcasting of arrays with different buffer types.

Add findnz & fix broadcasting

---

src/AMDGPU.jl

Import allowscalar

---

test/rocarray/fft.jl

[rocFFT] Verify that the input array is not modified for out-of-place methods

---

src/blas/highlevel.jl
src/sparse/array.jl
src/sparse/linalg.jl

Backport a few fixes from CUDA.jl.

Fix errors with istriu and istril

---

.buildkite/pipeline.yml
docs/src/quickstart.md

Re-enable the generic target of any AMDGPU CI machine

Test doc build on CI machine

---

.buildkite/pipeline.yml

Fix doc build CI

---

src/device/gcn/math.jl
test/device/math.jl

Fix fast min/max on 1.12

---

docs/Project.toml
docs/make.jl
docs/src/api/intrinsics.md
docs/src/api/memory.md
docs/src/api/printing.md
docs/src/index.md
docs/src/tutorials/perf.md
docs/src/tutorials/quickstart.md

- Update highlight box style
- Fix minor typos

Improve docs

---

src/discovery/utils.jl

Fix gpu-less CI

---

docs/src/install_tips.md

Since quite a few folks are running into issues on Archlinux (#696, #770, #767), I thought it would be good to point out the alternative shown in https://github.com/JuliaGPU/AMDGPU.jl/issues/770#issuecomment-3003954390

Add FAQ entry for AMDGPU on Archlinux

---

Project.toml
docs/Project.toml
docs/make.jl
docs/src/install_tips.md
docs/src/tutorials/perf.md

Docs preview: https://amdgpu.juliagpu.org/previews/PR807/

Add SIMD docs & re-include installation tips

---

Project.toml
docs/src/api/memory.md
docs/src/tutorials/perf.md
src/array.jl
src/runtime/memory/hip.jl
test/rocarray/base.jl

Update docs & fix `own` kwarg handling for `unsafe_wrap`
