- Project.toml
- docs/make.jl
- docs/src/exceptions.md
- docs/src/execution_control.md
- docs/src/memory.md
- src/AMDGPU.jl
- src/compiler.jl
- src/device/gcn.jl
- src/device/gcn/atomics.jl
- src/device/gcn/execution_control.jl
- src/device/gcn/hostcall.jl
- src/device/gcn/indexing.jl
- src/device/gcn/memory_dynamic.jl
- src/device/gcn/memory_static.jl
- src/device/gcn/output.jl
- src/device/pointer.jl
- src/device/runtime.jl
- src/device/tools.jl
- src/exceptions.jl
- src/execution.jl
- src/execution_utils.jl
- src/runtime.jl
- test/device/exceptions.jl
- test/device/execution_control.jl
- test/device/memory.jl
- test/device/output.jl
- test/hsa/global.jl
- test/runtests.jl
- test/util.jl
Removed support for LLVM < 7
Added memcpy! and memset! intrinsics
Added more efficient memcpy! implementation for output
Added global output context support
Added exception flag and exception list
Added malloc and free hostcalls
Added execution control intrinsics
Expanded ROCModule to contain exception ring buffer
Added HSAStatusSignal for exception handling
Worked around broken exception intrinsic emission
Todo:
> Improve kernel-thrown exceptions

- deps/deps.jl
- deps/hsa/build.jl
- deps/rocm-external/build.jl
- src/hip/HIP.jl
- src/hip/libhip.jl
These changes should allow the HIP library to load regardless of whether it uses the current or older naming convention.
The newer location of ROCm-provided `lld.ld` is also included in the search paths.
> fix for finding HIP binaries

- src/device/globals.jl
Apparently, LLVM's `appendToUsedList` (called from LLVMExtra via `LLVM.set_used!`) tries to bitcast from the provided GV to an `i8*`, which I assume is not valid when the GV has a non-0 addrspace. Whatever the reason, we've been getting an `Invalid constexpr bitcast!` assertion originating from that line in some tests and on all of my systems (which use an LLVM debug build +asserts).
Offending line in LLVM 9.0.1 is `lib/Transforms/Utils/ModuleUtils.cpp +87`.
@maleadt am I doing something wrong, or is LLVM?
> Don't do set_used on GVs

- Manifest.toml
- docs/make.jl
- docs/src/kernel_deps.md
- src/AMDGPU.jl
- src/device/gcn/hostcall.jl
- src/execution.jl
- src/execution_utils.jl
- src/kernel.jl
- src/queue.jl
- src/runtime.jl
- src/signal.jl
- test/device/deps.jl
- test/runtests.jl
Allows us to block a queue until either:
- All kernels in a set complete
- Any kernel in a set complete
This will be necessary for KernelAbstractions integration.
Fixes #63 in the process (and also preserves kernel arguments)
Todo:
> Add barrier packet support

- src/device/runtime.jl
Removes these annoying (and probably harmless) warnings:
```
'+fp64-fp16-denormals' is not a recognized feature for this target (ignoring feature)
'-fp32-denormals' is not a recognized feature for this target (ignoring feature)
```
> Remove annoying target-features for now

- src/device/runtime.jl
- src/execution.jl
- src/queue.jl
- test/device/launch.jl
We weren't `dispose`-ing our device-libs bitcode modules, so they just accumulated in memory, leading to >32GB memory allocated to run the tests. This brings it down to around 3GB (and further changes should be able to bring it down slightly further).
While troubleshooting, I also added `@roc launch=false ...` for returning the kernel object, which should be useful for more advanced users in some cases.
> Fix memory leak

- Project.toml
- src/AMDGPU.jl
- src/array.jl
- src/blas/rocBLAS.jl
- src/blas/wrappers.jl
- src/device/gcn/hostcall.jl
- src/execution.jl
- src/fft/fft.jl
- src/fft/rocFFT.jl
- src/rand/random.jl
- src/rand/rocRAND.jl
- src/signal.jl
- src/sync.jl
- test/rocarray/blas.jl
- test/rocarray/fft.jl
- test/rocarray/nmf.jl
- test/rocarray/random.jl
- test/runtests.jl
- test/util.jl
In CUDA, everything uses streams natively, and streams are in-order by default, so things "just work" when launching multiple kernels and using external libraries. With AMDGPU, we use non-blocking queues, however HIP-based libraries use their own stream-like system that uses their own blocking queues. We thus need some way to ensure ordering of operations.
This PR implements a system called "mark/wait", where performing an operation on/with a `ROCArray` "marks" the array as in-use, with a signal or stream becoming associated with that array. When another operation is performed on the array, all signals and streams that were marked on this array are waited on or synchronized, and then the operation will be performed. Notably, this allows us to mix kernel launches with HIP stream-based …
> Add mark/wait synchronization system

- src/device/runtime.jl
- src/exceptions.jl
Together with https://github.com/wsmoses/Enzyme.jl/pull/54 allows for using Enzyme.jl with AMGPU.jl
Still leaves us with:
```
warning: Linking two modules of different data layouts: '' is 'e-p:64:64-p1:64:64-p2:32:32-p3:32:32-p4:64:64-p5:32:32-p6:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64-S32-A5-ni:7-ni:10:11:12:13' whereas 'text' is 'e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128-ni:10:11:12:13'
warning: Linking two modules of different target triples: ' is 'amdgcn-amd-amdhsa' whereas 'text' is 'x86_64-pc-linux-gnu'
warning: Linking two modules of different data layouts: 'text' is 'e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128-ni:10:11:12:13' whereas 'text' is …
```
> fixes for delayed codegeneration

- src/array.jl
- test/runtests.jl
Only broken test seem to be:
```
reinterpret: Error During Test at /home/vchuravy/.julia/packages/GPUArrays/8dzSJ/test/testsuite/base.jl:140
Test threw exception
Expression: Array(Af0) == af0
StackOverflowError:
Stacktrace:
[1] Array
@ ./boot.jl:448 [inlined]
[2] Array
@ ./boot.jl:457 [inlined]
[3] similar
@ ./abstractarray.jl:750 [inlined]
[4] similar
@ ./abstractarray.jl:741 [inlined]
[5] copyto!(dest::Vector{Float32}, dstart::Int64, src::Base.ReinterpretArray{Float32, 1, ComplexF32, ROCVector{ComplexF32}, false}, sstart::Int64, n::Int64)
@ GPUArrays ~/.julia/packages/GPUArrays/8dzSJ/src/host/abstractarray.jl:128
[6] copyto!(dest::Vector{Float32}, dstart::Int64, src::Base.ReinterpretArray{Float32, 1, ComplexF32, ROCVector{ComplexF32}, false}, sstart::Int64, n::Int64) (repeats 79980 …
```
> run GPUArrays test-suite

- src/execution.jl
- test/device/launch.jl
Apparently we weren't propagating the device to `roccall`, leading to an inability to utilize multiple devices without switching the default device.
> Propagate device to roccall

- deps/build.jl
Ran into this before of not finding `ld.lld`. `ROCM_PATH` seems to be defined on those systems.
> Detect ROCM_PATH environment variable

- src/device/gcn/math.jl
The function overrides of `sqrt` and `abs` make only these methods available in the namespace of `AMDGPU` from `Kernelabstractions.jl`. This leads to `sqrt(::Float64)` for example missing in KA.
I assume other function overrides lead to the same behavior.
> Function overrides lead to undefined functions in KA

- src/device/gcn/math.jl
Like https://github.com/JuliaGPU/CUDA.jl/pull/1361
I am wondering if we could actually get rid of GCNIntrinsic, I find that style of metaprogramming
much harder to reason through.
> Define a map from gamma to tgamma

- .buildkite/pipeline.yml
- Project.toml
- src/AMDGPU.jl
- src/utils.jl
- test/runtests.jl
Implements `AMDGPU.functional()` and `AMDGPU.functional(::Symbol)`, which are now the de-facto methods for querying the overall functionality of AMDGPU, and of individual ROCm components, respectively.
@omlins
Closes #198
> utils: Add functional query

- src/agent.jl
- test/hsa/agent.jl
As requested by @luraess and @omlins for MPI integration
Also removes the very silly `set_default_agent!(#=empty=#)` API
> HSAAgent: Add device()/device!() API

- docs/src/memory.md
- src/agent.jl
- src/array.jl
- src/hsa/HSA.jl
- src/kernel.jl
- src/mapreduce.jl
- src/memory.jl
- test/hsa/memory.jl
Adds support for HSA's memory pools API, which works around the bug reported in https://github.com/RadeonOpenCompute/ROCR-Runtime/issues/134. We still use HSA's regions API for finegrained and kernarg allocations, because those aren't exposed via this API.
Also fixes #210 
Todo:
> HSA: Add memory pools API

- src/hsa/LibHSARuntime.jl
@michel2323 this should fix the missing agents on Crusher
> HSA: Don't always load hsa_rocr_jll

- src/execution_utils.jl
- src/extras.jl
- src/memory.jl
- test/hsa/agent.jl
- test/hsa/memory.jl
- test/runtests.jl
Provide an async memcpy function `AMDGPU.Mem.unsafe_copy3d!` analogous to CUDA.jl's `CUDA.Mem.unsafe_copy3d!`, relying on HSA's `AMDGPU.HSA.amd_memory_async_copy_rect` functionality. Adresses #204 
Co-authored by @utkinis
> Add async memcpy functionality

- src/array.jl
This PR adopts the same approach for view indices as in [CUDA.jl](https://github.com/JuliaGPU/CUDA.jl/blob/master/src/array.jl#L659) to reduce allocations.
Before:
```julia
julia> x = AMDGPU.rand(Float32, 1024, 1024);
julia> @time @view(x[1:1024, 1:1024]);
0.000010 seconds (3 allocations: 16.312 KiB)
```
This PR:
```julia
julia> x = AMDGPU.rand(Float32, 1024, 1024);
julia> @time @view(x[1:1024, 1:1024]);
0.000004 seconds (1 allocation: 64 bytes)
```
> Add BackToCPU struct to reduce 'view' allocations

- src/highlevel.jl
- test/hsa/device.jl
For querying the device ID of a given `ROCDevice`.
> device: Add device_id method

- src/AMDGPU.jl
- src/device/gcn.jl
- src/device/gcn/array.jl
- src/launch.jl
- src/memory.jl
- src/queue.jl
- test/device/array.jl
- test/runtests.jl
This automatically retries HSA allocations up to 3 times if they initially fail with an `OUT_OF_RESOURCES` code, with calls to the GC in-between to try to free up allocated objects.
@claforte @pxl-th
> Mem: Retry failing allocations

- test/rocarray/fft.jl
This PR does two things:
1. Adds several tests to ensure fft wrappers (i.e. direct calls to fft, ifft, _without_ explicit plan creation) work correctly
2. Restores skipped fft tests.
The second change is partially addressed by this existing PR (https://github.com/JuliaGPU/AMDGPU.jl/pull/175) but this PR restores a few other skipped tests in addition.
All tests pass on my system.
> Expand fft tests

- src/fft/fft.jl
- src/fft/util.jl
- test/rocarray/fft.jl
This code is duplicated from AbstractFFTs; no need to copy it. (Additionally, `Float16` was misspelled as `FLoat16`.)
Add tests for casting to complex floats for FFTs, and for handing Integer inputs.
Note: Float16 is not tested as the casting is broken upstream in AbstractFFTs.
> Remove code that duplicates AbstractFFTs; add tests for casting

- src/device.jl
- test/device/wavefront.jl
Previously this was hardcarded to a wavefrontsize of 64, however some older cards use 32.
> Run wavefront tests with detected wavefrontsize

- src/kernel-signal.jl
So that we don't preserve `ROCQueue` objects unnecessarily
> active_kernels: Use WeakKeyDict

- src/AMDGPU.jl
- src/utils.jl
On Julia 1.9 when using AMDGPU & ROCKernels in another project, ROCKernels fails to precompile (see error below). Specifically, it complains at `src/AMDGPU.jl:231`.
We can use `hsa_version()` function directly instead of storing it in the variable during `__init__`. I didn't see `libhsaruntime_version` being used anywhere else.
```
Precompiling project...
✗ ROCKernels
✗ INGP
1 dependency successfully precompiled in 14 seconds. 184 already precompiled.
ERROR: The following 2 direct dependencies failed to precompile:
INGP [3003bbbd-5e0c-4496-81c4-ba6063c314ae]
Failed to precompile INGP [3003bbbd-5e0c-4496-81c4-ba6063c314ae] to /home/pxl-th/.julia/compiled/v1.9/INGP/jl_Lzl3vl.
ERROR: LoadError: InitError: Evaluation into the closed module `AMDGPU` breaks incremental compilation because the …
```
> Fix precompilation

- src/device/gcn/hostcall.jl
- test/hsa/error.jl
- Do not rethrow `EOFError`.
This happens when Julia process is exiting, but hostcalls are sleeping.
This gets rid of confusing error messages at the end of program execution:
```
┌ Error: HostCall error
│   exception =
│    EOFError: read end of file
│    Stacktrace:
│     [1] wait
│       @ ./asyncevent.jl:155 [inlined]
│     [2] sleep(sec::Float64)
│       @ Base ./asyncevent.jl:240
│     [3] hostcall_host_wait(signal::ROCSignal; maxlat::Float64, timeout::Nothing)
│       @ AMDGPU.Device ~/.julia/dev/AMDGPU/src/device/gcn/hostcall.jl:441
│     [4] macro expansion
│       @ ~/.julia/dev/AMDGPU/src/device/gcn/hostcall.jl:325 [inlined]
│     [5] (::AMDGPU.Device.var"#90#91"{ROCDevice, Float64, Nothing, Bool, AMDGPU.Compiler.var"#43#47", DataType, DataType, AMDGPU.Device.HostCall{UInt64, …
```
> Do not rethrow EOF

- src/execution.jl
- src/highlevel.jl
- test/device/launch.jl
In [`macro roc`](https://github.com/JuliaGPU/AMDGPU.jl/blob/c85bc0a2ef0b9a939016a71e201c0ded0d1f58c1/src/highlevel.jl#L313) `signal_kwargs` does not contain `queue` argument, which leads to usage of the default queue in [`create_event`](https://github.com/JuliaGPU/AMDGPU.jl/blob/c85bc0a2ef0b9a939016a71e201c0ded0d1f58c1/src/highlevel.jl#L106) thus making `queue` args basically useless.
To fix this I added `:queue` to `signal_kwargs` and use signal's queue when calling kernels.
`:queue` in `compiler_kwargs` and `call_kwargs` is thus not needed.
> Use correct queue for kernels

- src/AMDGPU.jl
- src/device/gcn/array.jl
- src/hashing.jl
- src/kernel.jl
- test/hsa/hashing.jl
- test/runtests.jl
Switches kernarg argument hashing from `Base.hash` to custom `khash` implementation, which doesn't attempt to hash array contents. This implementation hashes mainly on argument types and array pointers, ensuring that two identical `ROCDeviceArray` objects (pointing to the same memory) hash to identical values.
> Implement kernel hashing system

- deps/bindeps.jl
Update the binders code to also search for `ROCM_PATH` as suggested by @jpsamaroo . This is needed to build AMDGPU using system libs on LUMI with Julia 1.8.2.
> Update bindeps search path

- src/AMDGPU.jl
Enforce following behaviour to decide whether to use artifact:
Allows `ENV` var to set LocalPreferences. If value mismatch, `ENV` var will override LocalPreferences value with warning.
> Prioritise ENV var to use or not artifacts

- .gitignore
- docs/src/memory.md
- src/compiler.jl
- src/highlevel.jl
- src/kernel.jl
- test/device/memory.jl
Allows dynamically allocating local memory at runtime, by doing something like:
```julia
function f(RA::ROCDeviceArray)
ptr = AMDGPU.Device.alloc_local(:my_shmem, Float32, 0) # 0 signals dynamic allocation
RB = ROCDeviceArray(length(RA), ptr)
end
```
Closes #304
> Add dynamic local memory support

- src/blas/librocblas.jl
- src/blas/librocblas_types.jl
- src/blas/wrappers.jl
- test/rocarray/blas.jl
- test/runtests.jl
- Fix outdated `rocblas_dgemmBatched` function names.
- Use c-call wrappers generated by Clang.
- Support batched gemm that operates not only on Array-of-ROCArrays but on 3D ROCArrays as well.
So now we can do this:
```julia
julia> x = AMDGPU.rand(Float32, 4, 4, 3);
julia> AMDGPU.rocBLAS.gemm_batched('N', 'N', x, x);
```
- Add GEMM & batched GEMM tests for all supported types.
- Fix half-precision GEMM.
- Fix incorrect `rocblas_half` type alias.
---
Posting this here for the reference.
Clang generator for rocBLAS:
```julia
using Clang.Generators
using rocBLAS_jll
include_dir = normpath(rocBLAS_jll.artifact_dir, "include")
rocblas_dir = joinpath(include_dir, "rocblas")
options = load_options("blas-generator.toml")
args = get_default_args()
push!(args, "-I$include_dir")
headers = [ …
```
> Fix GEMM (regular & batched) and support batched GEMM for 3D array

- src/blas/wrappers.jl
- test/rocarray/blas.jl
- test/runtests.jl
This PR adds support for 2D * 3D batched GEMM.
One use-case is applying the same `4x4` intrinsics matrix `K` to different extrinsics `4x4xN` matrices `[R|t]`.
> Add support for 2D * 3D batched GEMM

- src/blas/rocBLAS.jl
- src/blas/wrappers.jl
- test/rocarray/blas.jl
Turns out, NNlib internally reshapes 2D arrays to 3D and passes only 3D arrays to actual batched gemm implementations.
So this PR adjusts to that and drops 2D * 3D batched gemm support for simplicity.
> Support NNlib batched gemm format

- src/array.jl
- test/rocarray/blas.jl
- test/rocarray/fft.jl
This PR mean to resolve [issue](https://github.com/JuliaGPU/AMDGPU.jl/issues/319) by providing a `Base.pointer(::ROCArray)` method that correctly handles non-zero offsets.
(Honestly, I don't understand how the calls to `pointer(::ROCArray)` were working at all before??!)
Currently, the FFT test now passes, however, the the BLAS test still fails. Still attempting to work out why `pointer()` is not being called when performing matrix multiplication.
> Add pointer() method for ROCArray and some library tests

- src/array.jl
- src/device/gcn/hostcall.jl
- src/runtime/memory.jl
- test/rocarray/base.jl
This PR allows the behavior in CUDA.jl where a user/library can call `unsafe_free` on a `ROCArray`, which is useful for releasing GPU buffers early when it's guaranteed that they will no longer be used.
This also fixes the annoying ROCR warning `"Can't find address in allocation map"`, which was an off-by-one bug in `alloc_pooled` refcounting.
> Fix double unsafe_free calls

- src/runtime/executable.jl
The LLVM Ptr can't be directly compared to the C_NULL pointer - it needs to first be cast.
(Be warned, I have no idea what this code is doing, only that I encountered this bug during testing.)
> Cast to Ptr before checking NULL pointer

- src/array.jl
- src/runtime/error.jl
- src/runtime/kernel-signal.jl
- src/runtime/memory.jl
- src/runtime/signal.jl
- src/runtime/sync.jl
- test/rocarray/base.jl
Adds liveness tracking for each HSA/HIP pointer, and allows `unsafe_free!` to mark a pointer as dead; standard buffer refcounting will use this liveness marker to determine if the pointer should be freed.
Also fixes a refcounting off-by-one bug, excessive retains in derived array construction, and moves HSA refcount increment/decrement into memory allocation/free methods.
@pxl-th
> Fix `unsafe_free!` not actually freeing

- src/runtime/signal.jl
This removes excess allocations within the signal wait loop that would build up over time and slow down waiting.
> Reduce signal wait allocations

- .buildkite/pipeline.yml
- src/AMDGPU.jl
- src/highlevel.jl
- src/mapreduce.jl
- src/random.jl
- src/runtime/device.jl
- src/runtime/executable.jl
- src/runtime/kernel.jl
- src/runtime/queue.jl
- src/utils.jl
- test/device/output.jl
- test/device/wavefront.jl
- test/hsa/getinfo.jl
- test/runtests.jl
Makes `getinfo` more powerful by keeping track of the appropriate `Ref` eltype for all implemented info queries, and provides a generic interface which doesn't require passing a `Ref` object of the appropriate type.
> Implement unified getinfo interface

- deps/bindeps.jl
- src/highlevel.jl
- src/runtime/device.jl
- src/runtime/execution.jl
- src/runtime/kernel-signal.jl
- src/runtime/kernel.jl
- src/runtime/queue.jl
- src/runtime/signal.jl
Fixes various issues:
- `@roc` no longer synchronizes on kernel arguments when `launch=false`
- `wait` on the result of `@roc` now checks for and propagates queue errors
- Kernarg buffer writing happens just before launch, where ghost arguments have been eliminated
- Adds the missing `Runtime.device_wavefront_size` query for the generic `AMDGPU.wavefrontsize` call
> Assorted fixes

- src/runtime/kernel.jl
- src/runtime/memory.jl
Adds limiters for HSA memory allocations, and also for dynamic scratch memory allocations. The former is useful to detect where excessive allocations might be happening, and the latter is useful to ensure that we don't over-allocate scratch memory when it won't actually be used.
We also set a default scratch limit of 8192 bytes, down from the 16384 that the compiler chooses when including error paths.
> Add memory allocation limiters

- src/runtime/signal.jl
Because it's about 300X more expensive and probably uses more resources
> ROCSignal: Disable IPC by default

- src/mapreduce.jl
That only requires a single kernel vs. N copies for every block.
ref https://github.com/JuliaGPU/CUDA.jl/pull/1223
> Use broadcast instead of copies to initialize mapreduce buffers.

- src/blas/highlevel.jl
- test/rocarray/blas.jl
We had method definitions for:
`Transpose{T,UpperTriangular{T,ROCMatrix{T}}}`
But not for:
`LowerTriangular{T, Transpose{T, ROCMatrix{T}}}`
Which is what you get from:
```julia
julia> x = ROCArray(triu(rand(Float32, 4, 4)));
julia> x = transpose(UpperTriangular(x))
4×4 LowerTriangular{Float32, Transpose{Float32, ROCMatrix{Float32}}}:
0.939737    ⋅         ⋅         ⋅ 
0.0391901  0.184103   ⋅         ⋅ 
0.578203   0.059085  0.419264   ⋅ 
0.245061   0.34397   0.923544  0.710086
```
This PR adds those definitions for BLAS 2 & 3 as well as tests.
> Add blas wrappers for triangular matrix mul / div

- src/AMDGPU.jl
- src/runtime/signal.jl
- Use `LockedObject` instead of `ALLOC_SIGNAL_LOCK` global lock.
- Handle fetching from pool and pushing to pool in its own functions.
- Remove outer while loop in signal wait function.
Was the outer while loop to check `@assert AMDGPU.HSA_REFCOUNT[] > 0`?
Was there a situation where we had this issue?
- Rename `alloc_signal_pool_max` to `signal_pool_max_size` (IMO, but looks more descriptive).
> Simplify signal pooling

- src/blas/highlevel.jl
- src/blas/wrappers.jl
Previously, they were defined for `<:ROCBlasFloat` eltype which did not cover `Float16`, leading to generic mul pass for FP16 matrices.
- Before:
```julia
julia> using AMDGPU, BenchmarkTools, LinearAlgebra
julia> xf = AMDGPU.rand(Float16, 128, 128);
julia> @benchmark xf * xf
BenchmarkTools.Trial: 4885 samples with 1 evaluation.
Range (min … max):  254.892 μs … 16.584 ms  ┊ GC (min … max): 0.00% … 0.00%
Time  (median):     424.914 μs              ┊ GC (median):    0.00%
Time  (mean ± σ):     1.022 ms ±  2.802 ms  ┊ GC (mean ± σ):  0.00% ± 0.00%
█▃                                                            
██▇▃▃▅▃▁▁▁▃▁▃▁▄▄▁▁▁▁▁▁▃▁▁▁▁▁▃▃▁▁▃▁▁▁▄▃▄▄▅▄▅▆█▄▄▄▁▄▄▅▄▄▁▅▅▅▇█ █
255 μs        Histogram: log(frequency) by time        16 ms <
Memory estimate: 4.66 KiB, allocs estimate: 121.
```
- This …
> rocBLAS: define highlevel dot, gemm, axpy functions for FP16

- src/array.jl
- src/dnn/convolution.jl
- src/runtime/kernel.jl
- src/runtime/memory.jl
- Use workspace size suggested from `find_conv_algo` function.
Using `get_workspace_size` function for initial workspace allocation can lead to unncessary huge memory allocations (up to 2.5 GiB). Here's an example of convolution that led to 2.5 GiB workspace allocation.
```julia
c = Conv((3, 3), 1280=>1280) |> f16 |> gpu
x = rand(Float32, 32, 32, 1280, 1) |> f16 |> gpu
y = c(x)
```
Workspace size from `find_conv_algo` takes only ~15 MiB.
- Refactor allocation code a bit
> Fix huge MIOpen workspace allocations

- src/AMDGPU.jl
- src/array.jl
- src/dnn/softmax.jl
Fast softmax produces `NaN` values in FP16 mode on big arrays (e.g. 4096x4096)...
> Use accurate softmax

- src/runtime/kernel.jl
- src/runtime/linked-list.jl
- src/runtime/queue.jl
- Fix typo in `isempty` for list of active kernels.
- Move to the next kernel in the list only when done waiting on the previous kernel.
Previously this may have led to a following sync issue:
```
- monitor pops kernel to wait on, moves to the next kernel and starts waiting on the pop'd kernel
- host calls AMDGPU.synchronize(), but since it is empty it returns immediately
- monitor finishes waiting on pop'd kernel
```
- Remove scratch alloc limiter.
> Fix host synchronization

- docs/src/devices.md
- src/highlevel.jl
This PR adds `AMDGPU.device_id!` to allow switching device in the current task. It also extends the doc.
> Add device selection in current task by ID

- src/array.jl
- src/compiler/codegen.jl
- src/device/gcn/hostcall.jl
- src/device/gcn/output.jl
These were leftovers from before the TLS transition.
Fixes #425
> Remove buggy uses of default_device

- Project.toml
This was missed in #426.  I'd appreciate a new release after this is merged, so that this package can be used in Julia nightly :slightly_smiling_face:
> Declare compatibility with `LLD_jll` 15

- docs/src/profiling.md
- docs/src/quickstart.md
Fix and homogenise naming convention for using AMDGPU with HIP backend for kernel launch. Remove the statement about combat with CUDA naming which is not working.
> Fix docs for HIP

- test/runtests.jl
Ref https://github.com/JuliaGPU/KernelAbstractions.jl/issues/394.
> Allow specifying what tests to run

- src/hip/libhip.jl
- src/hip/libhip_common.jl
- src/runtime/memory/hip.jl
- test/rocarray/base.jl
Check if host memory pointer is still pinned before unregistering it in finalizer.
Fixes situation where two or more arrays wrap the same host buffer:
```julia
julia> using AMDGPU
julia> x = rand(Float32, 16);
julia> xd1 = unsafe_wrap(ROCArray, pointer(x), size(x));
[register] Ptr{Nothing} @0x00007f47bfedab40
julia> xd2 = unsafe_wrap(ROCArray, pointer(x), size(x));
[register] Ptr{Nothing} @0x00007f47bfedab40
julia> 
[unregister] Ptr{Nothing} @0x00007f47bfedab40
[unregister] Ptr{Nothing} @0x00007f47bfedab40
error in running finalizer: UndefVarError(var=:hipErrorInvalidResourceHandle)
ijl_undefined_var_error at /cache/build/default-amdci5-2/julialang/julia-release-1-dot-9/src/rtutils.c:132
ijl_get_binding_or_error at /cache/build/default-amdci5-2/julialang/julia-release-1-dot-9/src/module.c: …
```
> Check pointer is still pinned before unregistering it

- .buildkite/pipeline.yml
- src/compiler/codegen.jl
- src/compiler/device_libs.jl
- test/rocarray/base.jl
- Cache contents of devlib to avoid reading it every time there is linking.
- Do not link devlib if it is not needed.
This applies only to `("hc", "hip", "irif", "ockl", "opencl", "ocml")` devlibs, as other seem to be always required.
**Before (Julia 1.10):**
```
julia> @time sin.(x);
11.552189 seconds (30.58 M allocations: 1.394 GiB, 1.27% gc time, 59.74% compilation time: 2% of which was recompilation)
```
**After (Julia 1.10):**
```
julia> @time sin.(x);
7.220562 seconds (13.40 M allocations: 878.159 MiB, 1.49% gc time, 93.13% compilation time: 2% of which was recompilation)
```
> Optimize device lib linking

- src/blas/rocBLAS.jl
- src/fft/rocFFT.jl
Now:
```julia
julia> qr(A)
ERROR: ArgumentError: rocBLAS is not available
Stacktrace:
[1] lib_state()
@ AMDGPU.rocBLAS ~/.julia/dev/AMDGPU/src/blas/rocBLAS.jl:41
[2] handle()
@ AMDGPU.rocBLAS ~/.julia/dev/AMDGPU/src/blas/rocBLAS.jl:49
[3] geqrf!(A::ROCMatrix{ComplexF64, AMDGPU.Runtime.Mem.HIPBuffer})
@ AMDGPU.rocSOLVER ~/.julia/dev/AMDGPU/src/solver/highlevel.jl:13
[4] qr!(A::ROCMatrix{ComplexF64, AMDGPU.Runtime.Mem.HIPBuffer})
@ AMDGPU.rocSOLVER ~/.julia/dev/AMDGPU/src/solver/highlevel.jl:206
[5] qr(::ROCMatrix{ComplexF64, AMDGPU.Runtime.Mem.HIPBuffer}; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
@ LinearAlgebra ~/.julia/juliaup/julia-1.9.2+0.x64.linux.gnu/share/julia/stdlib/v1.9/LinearAlgebra/src/qr.jl:428
[6] qr(::ROCMatrix{ComplexF64, …
```
> blas: Improve error on missing rocBLAS

- src/AMDGPU.jl
- src/highlevel.jl
- src/hip/event.jl
- src/hip/libhip.jl
- test/runtests.jl
This PR adds the functionality to measure the elapsed time between two hip events. Inspired by CUDA.jl, it exposes a macro `AMDGPU.@elapsed` for end users.
I tested the new macro in a simple memory bandwidth benchmark (just copying/transferring memory) and it seems to work. That is, the resulting memory bandwidth is reasonable. ~However, what I'm unsure about is the line:~
```julia
t0, t1 = HIPEvent(C_NULL), HIPEvent(C_NULL)
```
~I chose `C_NULL` for the stream here (which according to [this](https://rocm-developer-tools.github.io/HIP/group__Event.html#gad4128b815cb475c8e13c7e66ff6250b7) waits for all commands on all streams to finish). But maybe that should be `AMDGPU.stream()` or something else?~
UPDATE: We use the task-local `stream()` instead of `C_NULL` now.
(cc @jpsamaroo, @luraess)
> `AMDGPU.@elapsed`

- src/hip/device.jl
- src/hip/libhip.jl
- test/runtests.jl
Similar to `CUDA.can_access_peer`, this PR introduces `AMDGPU.HIP.can_access_peer(device, peer)` to query whether one device can access another device.
> Expose `hipDeviceCanAccessPeer`

- src/array.jl
- test/rocarray/base.jl
Fixes for https://github.com/JuliaSmoothOptimizers/Krylov.jl/pull/781.
> Allow specifying buffer type in ctor

- docs/src/devices.md
- src/AMDGPU.jl
- src/highlevel.jl
- src/runtime/device.jl
- src/tls.jl
- test/hsa/device.jl
- test/hsa/getinfo.jl
- test/logging.jl
- test/runtests.jl
- test/tls.jl
Remove default device to simplify things.
Now the default device is the first device in the list returned by `AMDGPU.devices()`.
And when changing the device with `AMDGPU.device!` or `AMDGPU.device_id!`, IT becomes the default device for TLS.
CC @luraess.
> Remove default device stuff

- src/AMDGPU.jl
- src/gpuarrays.jl
- src/tls.jl
REPL displays values in a separate task which creates different TLS storage thus creating different HIP stream.
Perform device synchronization when displaying values in REPL mode.
Closes #500.
> Fix REPL display

- src/device/gcn/math.jl
This seems to make the optimization pipeline happier, though it's still the wrong ABI because it says it's an `i8*` instead of a `addresspace(5) float *` this also might need a change upstream to the allocopt pass
> Use refs instead of pointers to get a slightly friendlier abi

- docs/src/index.md
- src/rocm_discovery.jl
Mixed mode allows using ROCmDevice libraries from artifacts, but the rest of the libraries from system-wide installation.
Artifact device libraries were patched to be compatible with Julia LLVM.
This way you can run ROCm 5.6 (which uses LLVM 16) with Julia 1.10 (which uses LLVM 15).
Refer to `Requirements` section of the documentation for more instructions, but in short:
1. Add respective version of artifact device libraries in your project:
- ROCm 5.5: `]add ROCmDeviceLibs_jll@5.5`;
- ROCm 5.6: `]add ROCmDeviceLibs_jll@5.6`.
2. Call `AMDGPU.use_devlibs_jll!` in your Julia session to switch
to artifact device libraries (and the rest of the libraries
will be used from system-wide installation).
This should enable Navi 3 support (but I haven't tested it yet).
Thanks to @jpsamaroo for …
> Add ROCm mixed mode

- docs/src/api.md
- docs/src/hostcall.md
- docs/src/index.md
- docs/src/streams.md
- src/AMDGPU.jl
- src/compiler/codegen.jl
- src/highlevel.jl
- src/hip/HIP.jl
- src/hip/libhip.jl
- src/hip/libhip_common.jl
- src/hip/stream.jl
- test/device/hostcall.jl
- test/device/output.jl
- test/gpuarrays_tests.jl
- test/ka_tests.jl
Use non-blocking synchronization by default.
Waiting on a stream is done by launching host function on that stream, that triggers an event once it is processed, similar to how CUDA.jl does it.
This requires ROCm 5.4+, therefore we have a fallback that works on previous versions as well.
> Use non-blocking synchronization by default

- docs/src/api.md
- src/AMDGPU.jl
- src/compiler/codegen.jl
- src/compiler/device_libs.jl
- src/device/gcn/synchronization.jl
- src/hip/device.jl
- test/device/array.jl
- test/device/synchronization.jl
- test/device_tests.jl
- test/runtests.jl
~~Strangely on Navi 2 sometimes exactly one warp will fail to synchronize while every other warp succeedes...~~
Turns out we were always compiling kernels for the wavefront 64, which is not correct.
- Use correct wavefront size when compiling kernels.
- Add workgroup synchronization primitives: `sync_workgroup_count`, `sync_workgroup_and`, `sync_workgroup_or`.
- Only run hostcall tests on main thread. Move the rest of the device tests to a separate worker.
> Add workgroup synchronization primitives

- src/compiler/codegen.jl
- src/hip/device.jl
- Fixes #527 
- Link devlibs second time only when missing `okcl` intrinsics.
> Fix intial device fetching

- .buildkite/pipeline.yml
- src/device/gcn/hostcall.jl
Closes #537, #521.
`hipHostUnregister` and `hipHostFree` perform device synchronization under-the-hood: [link](https://github.com/ROCm-Developer-Tools/clr/blob/57cb8400583baa3aa2d30b53372894b3683c6474/hipamd/src/hip_memory.cpp#L1258).
So instead we defer freeing host buffers until the `HostCallHolder` finalizer.
> Defer freeing hostcall buffers & add 1.10 CI

- docs/src/hostcall.md
- src/device/gcn/hostcall.jl
- src/device/gcn/hostcall_utils.jl
- src/highlevel.jl
- test/device/hostcall.jl
- test/rocarray/base.jl
Closes #537.
Since both `hipHostUnregister` & `hipHostFree` perform device synchronization we can't call them inside hostcall tasks or in their finalizers.
Therefore, for now, have a separate `AMDGPU.Device.free!` method that will perform freeing of pinned host memory allocated by hostcalls.
> Have separate `free!` method for hostcalls

- docs/src/index.md
- src/AMDGPU.jl
- src/discovery/discovery.jl
- src/discovery/utils.jl
Previously we'd find all possible ROCm directories and then search in them.
This might lead to a mix of libraries from different ROCm directories.
Instead, we now rely on:
1. `Libdl.find_library` to find ROCm libraries
2. Look into standard ROCm path:
- Linux: `/opt/rocm`
- Windows: `C:/Program Files/AMD/ROCm/<version>`
3. If user has a non-standard path, then it can be specified with `ROCM_PATH` env variable.
> Simplify ROCm discovery

- src/sparse/helpers.jl
- src/sparse/types.jl
We need these constructors if we want to preallocate the buffers for sparse matrix-vector and sparse matrix-matrix products with just `A`.
> [rocSPARSE] Add new constructors

- src/array.jl
- src/fft/fft.jl
- src/hip/HIP.jl
- src/hip/stream.jl
- src/runtime/Runtime.jl
- src/runtime/memory/hip.jl
- src/tls.jl
- src/utils.jl
- test/device/output.jl
- test/device_tests.jl
- test/hip_core_tests.jl
- test/hip_extra_tests.jl
- test/runtests.jl
- Check HIP context is valid before reeing HIP streams, arrays in finalizer.
- Do not `dlopen` in `versioninfo` since we already have absolute paths.
- Disable device printing tests on 1.11 for now, see #551.
- Split HIP tests into two to allow parallel processing.
> Check context is valid before freeing streams, arrays.

- gen/rocsparse/generator.jl
- gen/rocsparse/rocsparse-generator.toml
- src/hip/HIP.jl
- src/sparse/generic.jl
- src/sparse/librocsparse.jl
- src/sparse/librocsparse_common.jl
- src/sparse/librocsparse_deprecated.jl
- src/sparse/rocSPARSE.jl
- test/hip_extra_tests.jl
Closes #571.
Seems that only generic `spmv` required an update.
- Use new stage parameter in `spmv` method.
- Add rocSPARSE wrapper generator.
> Update rocSPARSE to ROCm 6

- gen/rocsolver/generator.jl
- gen/rocsolver/rocsolver-generator.toml
I can't test it with ROCm 6.0 but it could be possible to generate `librocsolver.jl` with the updated headers.
> Add a generator for ROCsolver

- src/runtime/hip-execution.jl
Before:
```julia
julia> @time fill!(x, 1f0);
0.000039 seconds (26 allocations: 1.180 KiB)
```
This PR:
```julia
julia> @time fill!(x, 1f0);
0.000028 seconds (5 allocations: 408 bytes)
```
> Fix kernel launch inference

- src/blas/highlevel.jl
Keeping the defaults to alpha = 1 and beta = 0 should mean this does not affect current API usage, but ensures LinearAlgebra.mul! does not fall back to general matrix multiply methods when passing in `ROCMatrix`s.
> Expose alpha and beta parameters in LinearAlgebra.mul!

- src/solver/highlevel.jl
- test/rocarray/solver.jl
I mistakenly returned the transpose of `V` in the SVD wrappers instead of the adjoint, which this PR fixes.
The unit tests I wrote didn't catch this because they used the transpose on `V` as well.
> Use adjoint instead of tranpose when returning V in SVD

- src/compiler/dynamic_memory.jl
- src/compiler/exceptions.jl
- src/compiler/output_context.jl
- src/device/gcn/hostcall.jl
- src/exception_handler.jl
> Use default flag during host malloc

- docs/src/kernel_programming.md
- src/compiler/codegen.jl
- src/highlevel.jl
- src/runtime/hip-execution.jl
Default to 'unsafe' hardware floating-point atomics.
TL;DR instead of emulating them via CAS loop use hardware RWM instruction that is **significantly** faster.
More details: [link](https://docs.amd.com/projects/HIP/en/docs-5.3.0/reference/kernel_language.html#unsafe-floating-point-atomic-rmw-operations).
E.g. assembly atomic instruction before & after this PR for the following kernel:
```julia
function ker!(x)
@inline @atomic x[1] += 1f0
return
end
```
- Before: `global_atomic_cmpswap_b32 v0, v2, v[0:1], s[0:1] glc`
- After: `global_atomic_add_f32 v0, v1, s[0:1]`
I'm inclined to make this a default because of huge performance increase.
On [Nerf.jl](https://github.com/JuliaNeuralGraphics/Nerf.jl) benchmark this gives ~2x performance improvement and on yet-unreleased GaussianSplatting.jl …
> Default to hardware floating-point atomics.

- src/blas/highlevel.jl
- test/rocarray/blas.jl
- Use function arguments instead of captured variables, otherwise we mix CPU & GPU arrays and segfault:
```diff
-@test testf((a, b) -> f(TR(A)) * b, A, x)
+@test testf((a, b) -> f(TR(a)) * b, A, x)
```
- Add matrix inversion for triangular & diagonal matrices.
- Make generic trimatmul more specific. Supersedes #626.
> Fix blas tests

- src/AMDGPU.jl
- src/hip/HIP.jl
- src/hip/event.jl
- src/hip/libhip.jl
- src/hip/libhip_common.jl
- src/hip/pool.jl
- src/hip/stream.jl
- src/runtime/memory/hip.jl
- src/runtime/memory/utils.jl
- src/sparse/types.jl
- src/stats.jl
Implements `maybe_collect` mechanism and reworks hard memory limit to be more robust.
Closes #625.
> Rework hard memory limit & add maybe collect mechanism

- src/dnn/MIOpen.jl
- test/dnn/miopen.jl
- test/dnn/softmax.jl
- test/runtests.jl
NNlib has pure Julia implementation for both and MIOpen softmax has issues: https://github.com/ROCm/MIOpen/issues/2966
> Remove MIOpen softmax & batchnorm

- src/AMDGPU.jl
- src/array.jl
- src/blas/wrappers.jl
- src/compiler/dynamic_memory.jl
- src/compiler/exceptions.jl
- src/compiler/output_context.jl
- src/device/gcn/hostcall.jl
- src/exception_handler.jl
- src/gpuarrays.jl
- src/hip/stream.jl
- src/memory.jl
- src/runtime/memory/hip.jl
- test/rocarray/base.jl
- Add Managed struct that keeps track of TLS streams and correctly switches between them. This in turn allows us to **not** use global stream in finalizers.
Ref: https://github.com/JuliaGPU/CUDA.jl/issues/2236
Allows us to use tls streams in finalizers instead of global one.
- Remove REPL hook.
> Keep track of stream usage for arrays

- docs/src/index.md
- src/memory.jl
Either call `AMDGPU.eager_gc!(false)` or set in `LocalPreferences.toml` file following:
```toml
[AMDGPU]
eager_gc = false
```
@luraess
> Allow disabling eager GC

- Project.toml
- src/array.jl
Fixes:
```julia
ROCArray{ComplexF32, 2, AMDGPU.Runtime.Mem.HIPBuffer}([1, 2, 3, 4])
```
> Add ctor with buffer type

- src/array.jl
- src/dnn/convolution.jl
- src/runtime/memory/hip.jl
Fixes algorithm selection to select the best candidate.
```julia
c = ConvTranspose((16,), 128 => 64; stride=8, pad=4) |> gpu
x = gpu(rand(Float32, 256, 128, 32))
c(x)
```
- Before (using naive algorithm): `85ms 927us 783ns`
- Now (using GEMM): `635us 82ns`
**Note:** might require deleting your `~/.cache/miopen` to regenerate algorithm database, since it is persistent.
> Properly allocate workspace for conv algo search

- src/compiler/codegen.jl
Add missing comma when concatenating compile target features resulting in:
```
'+sramecc-wavefrontsize32' is not a recognized feature for this target (ignoring feature)
```
CC @pedrovalerolara
> Fix feature concatenation

- src/array.jl
- test/rocarray/base.jl
Currently the `ROCArray` constructor returns its argument unlike `Array`'s constructor. This change uses `copy` instead.
```jl
julia> let x = rand(5)
y = Array(x)
z = Array(y)
y === z
end
false
julia> let x = rand(5)
y = ROCArray(x)
z = ROCArray(y)
y === z
end
true
```
> copy in constructor

- src/AMDGPU.jl
Changes the `ENV[string]` lookups to a `get()` with a default of "0". This prevents the `ERROR: InitError: KeyError: key "JULIA_AMDGPU_CORE_MUST_LOAD" not found` when running outside of the CI.
For example, previously I was getting 
```
julia> using AMDGPU
┌ Warning: HSA runtime is unavailable, compilation and runtime functionality will be disabled.
└ @ AMDGPU ~/.julia/packages/AMDGPU/a1v0k/src/AMDGPU.jl:205
ERROR: InitError: KeyError: key "JULIA_AMDGPU_CORE_MUST_LOAD" not found
Stacktrace: ...
```
With this PR, I'm getting
```
julia> using AMDGPU
┌ Warning: HSA runtime is unavailable, compilation and runtime functionality will be disabled.
└ @ AMDGPU ~/.julia/packages/AMDGPU/zQy5G/src/AMDGPU.jl:205
...
julia> AMDGPU.functional()
false
```
as I would have expected for this case.
> Prevent crash when libraries are unavailable during __init__

- gen/Project.toml
- gen/hip/generator.jl
- gen/miopen/generator.jl
- gen/miopen/miopen-generator.toml
- gen/rocblas/generator.jl
- gen/rocblas/rocblas-generator.toml
- gen/rocfft/generator.jl
- gen/rocfft/rocfft-generator.toml
- gen/rocsolver/generator.jl
- gen/rocsolver/rocsolver-generator.toml
- gen/rocsparse/generator.jl
- gen/rocsparse/rocsparse-generator.toml
- src/blas/librocblas.jl
- src/solver/highlevel.jl
- src/solver/librocsolver.jl
- src/solver/rocSOLVER.jl
- src/sparse/librocsparse.jl
@pxl-th 
I also improved the files `generator.jl` for each library.
> Generate librocsolver.jl with Clang.jl

- src/blas/librocblas.jl
- src/discovery/discovery.jl
- src/dnn/libMIOpen.jl
- src/solver/librocsolver.jl
- Fix import on non-functional machines (close #685).
- Add `@check` back to `ccall` (removed by #617).
> Fix import on non-functional machines

- src/fft/fft.jl
- test/rocarray/fft.jl
This PR fixes the execution of an FFT plan on a different AMDGPU stream (or Julia task) from the one used to create the plan.
Example:
```julia
using AMDGPU
using AbstractFFTs
x = ROCArray(rand(Float32, 100, 200))
p = plan_rfft(x)
y = p * x
task = Threads.@spawn p * x   # this currently fails! (switches to a different stream)
z = fetch(task)
Array(z) == Array(y)  # should be true
```
This currently fails simply because the `info` variable is not defined in `update_stream!`.
> Fix FFT execution on separate Julia task

- .buildkite/pipeline.yml
- Project.toml
- src/ROCKernels.jl
- src/device/gcn/array.jl
- test/device/array.jl
Required for things like `strides(::ROCDeviceArray)` to work.
> Adapt ROCDeviceArray to DenseArray interface

- src/AMDGPU.jl
- src/discovery/discovery.jl
- src/utils.jl
Fixes #690. Rocalution is currently not used by AMDGPU.jl and using a system library with a different MPI then the rest of Julia will not work. For now just prefer `librocalution_hip`.
> Prefer librocalution_hip over librocalution

- src/sparse/interfaces.jl
- test/rocsparse/interfaces.jl
> Update ROCSparse for Julia v1.10

- src/sparse/broadcast.jl
`Vararg{<:Any, N}` should be `Vararg{Any, N}`
> fix `Vararg{<:Any, N}`

- src/blas/highlevel.jl
- src/dnn/convolution.jl
- src/hip/HIP.jl
- src/memory.jl
- src/runtime/memory/hip.jl
- Revert `maybe_collect` to old behavior. Current one is too aggressive.
- Fixes #697.
@jariji, this PR reduces the amount of locks taken, so there should be no locks in the finalizer. Feel free to re-open the issue, if you are still seeing the errors after this PR.
- Add `istriu` methods for `ROCArray` to fix triangular `lmul!` in 1.11.2.
> Take fewer locks

- docs/src/index.md
It took me quite some searching and experimenting to figure out how the Fedora rocm packages can be leveraged from Julia. I found the answer and would like to share it in the documentation - there seems to be a quite appropriate place for it (the one I'd been staring at before).
> Add hint about ROCM_PATH to documentation

- src/discovery/discovery.jl
- src/discovery/utils.jl
- src/runtime/Runtime.jl
- src/utils.jl
And remove some sketchy code for artifact loading.
Closes #721.
@BSchilperoort, hopefully fixes the issue. If you can test and confirm that'd be great!
> Fix libhib discovery for Windows

- src/fft/fft.jl
Similar to the PR in CUDA.jl:
https://github.com/JuliaGPU/CUDA.jl/pull/2578
> [rocFFT] Don't perform a copy for each call of FFT

- src/device/gcn/array.jl
- src/device/quirks.jl
- test/device/array.jl
> Override `Base._throw_dmrs` to avoid dynamic string allocation

- src/fft/fft.jl
- test/rocarray/fft.jl
This PR fixes a couple of type inference issues when creating FFT plans. It is nearly identical to a [recently merged PR](https://github.com/JuliaGPU/CUDA.jl/pull/2683) for CUDA.jl.
In particular, it fixes an issue related to the uninferred number of dimensions of the buffer array introduced in #728.
> Fix inference of FFT plan creation

- src/hip/HIP.jl
- src/memory.jl
Closes #738 
Wondering if we should get rid of it completely given that we have caching allocator now.
> Disable maybe_collect if failed to get free memory

- src/AMDGPU.jl
I wanted to use `StridedROCVector` in a project and I remarked that only `StridedROCMatrix` was exported.
This PR exports the same symbols than `CUDA.jl`.
> Export more types

- src/runtime/memory/hip.jl
The issue in HIP got resolved as of ROCm 6.0 https://github.com/ROCm/hip/issues/3289#issuecomment-1920700024
> HIP fix for unsafe_copy3d

- src/AMDGPU.jl
- src/ROCKernels.jl
- src/device/Device.jl
- src/device/gcn/synchronization.jl
KA.__synchronize also has memory barrier semantics and should be
equivalent to OpenCL's `barrier(CLK_LOCAL_MEM_FENCE)`.
x-ref: https://github.com/JuliaGPU/OpenCL.jl/pull/300
This fixes the data-races I observed in https://github.com/JuliaGPU/AcceleratedKernels.jl/issues/41#issuecomment-2995688972
> Add memory barrier semantics to `sync_workgroup`

- src/device/gcn/output.jl
- test/device/output.jl
Get rid of `pointer_from_objref` from `printf` implementation since we only need to support a narrow set of types. It causes issues with 1.11+.
This also allows re-enabling proper exception reporting which will come in a separate PR.
CC @simeonschaub
> Fix printf on 1.11+

- docs/src/index.md
- docs/src/install_tips.md
- src/discovery/discovery.jl
- src/discovery/utils.jl
This builds on top of https://github.com/JuliaGPU/AMDGPU.jl/pull/775 but detects the libs automatically. It also detects the device libs if one ever wants to use the native rocm libs for this.
I tested that this works on my local fedora install
Closes #579
> Refactor initialization logic to allow for automatic detection in Fedora

- docs/src/index.md
- docs/src/install_tips.md
Installing the non-devel packages only works just fine for me. I also deleted rccl from the list since AFAIK, we don't support it atm (ref #651). It can always be added back once we can make use of it.
> follow up #788, improve docs

- docs/src/install_tips.md
- src/memory.jl
Instead (IMO) we should encourage users to use [`GPUArrays.@cached`](https://amdgpu.juliagpu.org/dev/tutorials/perf#Use-Caching-Memory-Allocator) if they care about VRAM consumption and performance.
> Disable eager GC by default

- src/solver/highlevel.jl
- test/rocarray/solver.jl
> [rocSOLVER] Interface geblttrf_npvt and geblttrs_npvt

- src/blas/highlevel.jl
The linked LinearAlgebra.jl method only defines this for `StridedMatrix`
as first argument and `tA` and `tB` restricted to `AbstractChar`, same
goes for the fallback GPUCompiler.jl method as well as JuliaGPU/CUDA.jl#2888.
Should fix the ambiguity errors we are seeing on CI
> fix ambiguity error in Julia 1.12

- src/blas/wrappers.jl
- test/rocarray/blas.jl
A bunch of stuff in `gemm_batched` needed fixing/tests and a few other things are now tested as well.
> Even more BLAS tests and fixes
